#!/bin/sh


FILES="errorReport.ml syntree.ml parse.mli parse.ml lex.ml \
       symtbl.ml codegen.ml semant.ml x86asm.ml main.ml"

OCAMLYACC=ocamlyacc
OCAMLLEX=ocamllex
OCAMLC=ocamlc.opt
OCAMLOPT=ocamlopt.opt

$OCAMLYACC -v *.mly
$OCAMLLEX *.mll

$OCAMLC -c -g $FILES
#$OCAMLOPT -c $FILES

